# main text of home
name: Teknologihuset
bio: Teknologihuset

# twitter summary info
description: Homepage of Teknologihuset

picture: assets/images/profile.jpg

url: https://javabin.github.io/teknologihuset
timezone: Europe/Oslo

permalink: /:title/

markdown: kramdown

excerpt_separator: <!--more-->

feed:
  excerpt_only: true

# default settings pr page and post
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      picture: assets/images/someimage.jpg
      heading: "Teknologihuset"
      subheading: "House of Communities"
      bio: ""
      social: true
      animation: true
  -
   scope:
     path: ""
     type: "posts"
   values:
     someOption: "Default value of some option."

# To enable google analytics, supply your token below
#analytics-google: 'UA-87052810-1'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, set to false
disqus: false

# if you don't have any of social below, comment the line
# facebook: teknologihuset
twitteruser: teknologihuset
instagram: teknologihuset
# pinterest: mypinterest
linkedin: teknologihuset
# youtube: myyoutube
# spotify: myspotify
github: teknologihuset
# medium: medium
#vimeo: teknologihuset
email: vert@teknologihuset.no

authors:
    dervism:
        name: Dervis Mansuroglu
        bio: Developer, Community Lead and Meetup Organizer.
        picture: assets/images/dervis.jpg
        twitter: dervis_m

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# show next & prev links in blog post?
blog-nav-links: true

sass:
    sass_dir: _sass
    style: :compressed

# seo tag - twitter card
twitter:
  username: teknologihuset
  card: summary

# seo tag - social profiles
social:
  name: Teknologihuset
  links:
    - https://twitter.com/teknologihuset
    - https://www.linkedin.com/in/teknologihuset
    - https://github.com/teknologihuset

logo: assets/images/profile.jpg

exclude: ['package.json', 'initpost.sh', 'README.md', 'Gemfile', 'Gemfile.lock', '.jekyll-cache']

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
